export const labels = new Map([
  ['', '-'],
  ['seconde', 'Seconde Générale et Technologique'],
  ['premiere-g', 'Première Générale'],
  ['premiere-t', 'Première Technologique'],
  ['terminal-g', 'Terminale Générale'],
  ['terminal-t', 'Terminale Technologique'],
  ['2nd1', '2nd1'],
  ['2nd2', '2nd2'],
  ['2nd3', '2nd3'],
  ['2nd4', '2nd4'],
  ['2nd5', '2nd5'],
  ['2nd6', '2nd6'],
  ['2nd7', '2nd7'],
  ['2nd8', '2nd8'],
  ['2nd9', '2nd9'],
  ['1g1', '1G1'],
  ['1g2', '1G2'],
  ['1g3', '1G3'],
  ['1g4', '1G4'],
  ['1g5', '1G5'],
  ['1g6', '1G6'],
  ['1stl', '1STL'],
  ['1std2a', '1STD2A'],
  ['tg1', 'TG1'],
  ['tg2', 'TG2'],
  ['tg3', 'TG3'],
  ['tg4', 'TG4'],
  ['tg5', 'TG5'],
  ['tg6', 'TG6'],
  ['tstl', 'TSTL'],
  ['tstd2a', 'TSTD2A'],
  ['stl', 'STL'],
  ['std2a', 'STD2A'],
  ['ap-spe', 'Arts Plastiques'],
  ['cav-spe', 'Cinéma AudioVisuel'],
  ['ghhsp-spe', 'Histoire-Géographie, Géopolitique et Science Poilitique'],
  ['hlp-spe', 'Humanité, Littérature et Philosophie'],
  ['llce-spe', 'Langues, Littératures et Cultures Etrangère'],
  ['llca-spe', 'Littératures, Langues et Cultures de l\'Antiquité'],
  ['maths-spe', 'Mathématiques'],
  ['nsi-spe', 'Numérique et Science de l\'Informatique'],
  ['pc-spe', 'Physique-Chimie'],
  ['svt-spe', 'Science de la Vie et de la Terre'],
  ['ses-spe', 'Science Economique et Sociales'],
  ['bb-tspe', 'Biochimie-Biologie'],
  ['pcm-tspe', 'Physique-Chimie et Mathématiques'],
  ['spcl-tspe', 'Sciences Physiques et Chimiques en Laboratoire'],
  ['dma-tspe', 'Design et Métiers d\'Arts'],
  ['onl-tspe', 'Outils et Langages Numériques'],
  ['pc-tspe', 'Physique-Chimie'],
  ['amd-tspe', 'Analyse et Méthodes en Design'],
  ['ccdma-tspe', 'Conception et Création en Design et Métiers d\'Arts'],
  ['alld-lv', 'Allemand'],
  ['angl-lv', 'Anglais'],
  ['esp-lv', 'Espagnol'],
  ['ccd-opt', 'Création Cultures Design'],
  ['sl-opt', 'Science Laboratoire'],
  ['ap-opt', 'Arts Plasitiques'],
  ['cav-opt', 'Cinéma AudioVisuel'],
  ['mathsSpe-opt', 'Mathématiques Spécifiques'],
  ['maths-expert-opt', 'Mathématiques Expertes'],
  ['maths-compl-opt', 'Mathématiques Complémentaires'],
  ['chinois-opt', 'Chinois'],
  ['alld-euro', 'Allemand'],
  ['angl-euro', 'Anglais'],
  ['esp-euro', 'Espagnol'],
  ['eps-dnl', 'Education Physique et Sportive'],
  ['hist-dnl', 'Histoire-Géographie'],
  ['maths-dnl', 'Mathématiques'],
  ['ses-dnl', 'Sciences Economique et Sociale'],
  ['fr', 'Français'],
  ['maths', 'Mathématiques'],
  ['pc', 'Physique-Chimie'],
  ['ses', 'Sciences Economique et Sociale'],
  ['snt', 'Sciences Numérique et Technologique'],
  ['svt', 'Sciences de la Vie et de la Terre'],
  ['es', 'Enseignement Scientifique'],
  ['philo', 'Philosophie'],
  ['emc', 'Enseignement Morale et Civique'],
  ['eps', 'Education Physique et Sportive'],
  ['hist', 'Histoire-Géographie'],
  ['m', 'Masculin'],
  ['f', 'Féminin'],
  ['n', 'Non Précisé'],
])

export const correspondingTable = new Map([
  ['fr', ['fr']],
  ['maths', ['maths', 'mathsSpe-opt', 'maths-compl-opt', 'maths-dnl']],
  ['pc', ['pc']],
  ['ses', ['ses']],
  ['snt', ['snt']],
  ['svt', ['svt']],
  ['es', ['es', 'maths', 'pc', 'svt']],
  ['philo', ['philo', 'hlp-spe']],
  ['hist', ['hist', 'hist-dnl']],
  ['alld-lv', ['alld-lv', 'alld-euro']],
  ['angl-lv', ['angl-lv', 'angl-euro']],
  ['esp-lv', ['esp-lv', 'esp-euro']],
  ['ap-spe', ['ap-spe', 'ap-opt', 'amd-tspe', 'dma-tspe', 'ccdma-tspe', 'ccd-opt']],
  ['cav-spe', ['cav-spe', 'cav-opt']],
  ['ghhsp-spe', ['ghhsp-spe', 'hist']],
  ['hlp-spe', ['hlp-spe', 'fr']],
  ['llce-spe', ['llce-spe', 'angl-lv', 'angl-euro']],
  ['maths-spe', ['maths-spe', 'maths', 'mathsSpe-opt', 'maths-compl-opt', 'pcm-tspe', 'sl-opt', 'maths-dnl']],
  ['nsi-spe', ['nsi-spe', 'snt', 'onl-tspe']],
  ['pc-spe', ['pc-spe', 'es', 'pc', 'pcm-tspe', 'spcl-tspe', 'pc-tspe', 'sl-opt']],
  ['svt-spe', ['svt-spe', 'es', 'svt', 'bb-tspe', 'sl-opt']],
  ['ses-spe', ['ses-spe', 'ses', 'ses-dnl']],
  ['bb-tspe', ['bb-tspe', 'svt-spe', 'es', 'svt', 'sl-opt']],
  ['pcm-tspe', ['pcm-tspe', 'pc-spe', 'es', 'pc', 'pc-tspe', 'sl-opt']],
  ['spcl-tspe', ['spcl-tspe', 'pc-spe', 'es', 'pc', 'pc-tspe', 'sl-opt']],
  ['dma-tspe', ['dma-tspe', 'ap-spe', 'ap-opt', 'ccd-opt']],
  ['onl-tspe', ['onl-tspe', 'snt']],
  ['pc-tspe', ['pc-tspe', 'pcm-tspe', 'pc-spe', 'es', 'pc', 'sl-opt']],
  ['amd-tspe', ['amd-tspe', 'ap-spe', 'ap-opt', 'dma-tspe', 'ccdma-tspe', 'ccd-opt']],
  ['ccdma-tspe', ['ccdma-tspe', 'ap-spe', 'ap-opt', 'amd-tspe', 'dma-tspe', 'ccd-opt']],
  ['ccd-opt', ['ccd-opt']],
  ['sl-opt', ['sl-opt']],
  ['ap-opt', ['ap-opt']],
  ['cav-opt', ['cav-opt']],
  ['mathsSpe-opt', ['mathsSpe-opt', 'maths', 'sl-opt', 'maths-dnl']],
  ['maths-expert-opt', ['maths-expert-opt', 'maths-spe', 'maths', 'mathsSpe-opt', 'maths-compl-opt', 'pcm-tspe', 'sl-opt', 'maths-dnl']],
  ['maths-compl-opt', ['maths-compl-opt', 'maths-spe', 'maths', 'mathsSpe-opt', 'pcm-tspe', 'sl-opt', 'maths-dnl']],
  ['chinois-opt', ['chinois-opt']],
  ['alld-euro', ['alld-euro', 'alld-lv']],
  ['angl-euro', ['angl-euro', 'angl-lv']],
  ['esp-euro', ['esp-euro', 'esp-lv']],
  ['eps-dnl', ['eps-dnl']],
  ['hist-dnl', ['hist-dnl']],
  ['maths-dnl', ['maths-dnl']],
  ['ses-dnl', ['ses-dnl']],
])
