// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdSense: typeof import('./components/publicity/AdSense.vue')['default']
    Button: typeof import('./components/input/Button.vue')['default']
    Checkbox: typeof import('./components/input/Checkbox.vue')['default']
    CheckboxSchedule: typeof import('./components/schedule/CheckboxSchedule.vue')['default']
    Entry: typeof import('./components/input/Entry.vue')['default']
    Footer: typeof import('./components/parts/Footer.vue')['default']
    GoogleAuth: typeof import('./components/auth/GoogleAuth.vue')['default']
    InfoBar: typeof import('./components/parts/NavBar/InfoBar.vue')['default']
    InputSchedule: typeof import('./components/schedule/InputSchedule.vue')['default']
    LabelValue: typeof import('./components/pages/search/LabelValue.vue')['default']
    LabelValues: typeof import('./components/pages/search/LabelValues.vue')['default']
    Loading: typeof import('./components/style/Loading.vue')['default']
    LoginBar: typeof import('./components/parts/NavBar/LoginBar.vue')['default']
    PlanningInit: typeof import('./components/pages/login/PlanningInit.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Schedule: typeof import('./components/schedule/Schedule.vue')['default']
    SchoolInit: typeof import('./components/pages/login/SchoolInit.vue')['default']
    SearchUser: typeof import('./components/pages/search/SearchUser.vue')['default']
    Select: typeof import('./components/input/Select.vue')['default']
    SideBar: typeof import('./components/parts/NavBar/SideBar.vue')['default']
    TopBar: typeof import('./components/parts/NavBar/TopBar.vue')['default']
  }
}
